format = """
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$dotnet\
$nodejs\
$cmd_duration $jobs $time\
$line_break\
$character"""

[nodejs]
format = "[$symbol($version )]($style)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"

# Replace the "❯" symbol in the prompt with "❯❯"
[character]
format = "[❯❯](bold green) "
success_symbol = "[❯❯](bold green) "
error_symbol = "[❯❯](bold red) "

[package]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[time]
disabled = false
format = "[$time]($style)"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 2
truncate_to_repo = false
truncation_symbol = "/"

[username]
disabled = true

[dotnet]
symbol = '.NET '
style = 'green'
heuristic = true
version_format = 'v${raw}'
